import spoqaHanSansNeo from "@/styles/local.font";
import "@/styles/globals.scss";

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={spoqaHanSansNeo.className}>{children}</body>
    </html>
  );
}
