export const ADDRESS_1 = [
  { id: 0, label: "서울시 강동구" },
  { id: 1, label: "서울시 종로구" },
  { id: 2, label: "서울시 중구" },
  { id: 3, label: "서울시 용산구" },
  { id: 4, label: "서울시 성동구" },
  { id: 5, label: "서울시 광진구" },
  { id: 6, label: "서울시 동대문구" },
  { id: 7, label: "서울시 중랑구" },
  { id: 8, label: "서울시 성북구" },
  { id: 9, label: "서울시 강북구" },
  { id: 10, label: "서울시 도봉구" },
  { id: 11, label: "서울시 노원구" },
  { id: 12, label: "서울시 은평구" },
  { id: 13, label: "서울시 서대문구" },
  { id: 14, label: "서울시 마포구" },
  { id: 15, label: "서울시 양천구" },
  { id: 16, label: "서울시 강서구" },
  { id: 17, label: "서울시 구로구" },
  { id: 18, label: "서울시 금천구" },
  { id: 19, label: "서울시 영등포구" },
  { id: 20, label: "서울시 동작구" },
  { id: 21, label: "서울시 관악구" },
  { id: 22, label: "서울시 서초구" },
  { id: 23, label: "서울시 강남구" },
  { id: 24, label: "서울시 송파구" },
];
